import time
import requests
import logging
import jwt

logger = logging.getLogger(__name__)

VERDICT_TO_LABEL = {
    "GO FOR IT": "go-for-it",
    "STRETCH": "stretch",
    "NOT YET": "not-yet",
}


def _get_app_token(app_id, private_key, installation_id):
    now = int(time.time())
    payload = {
        "iat": now - 60,
        "exp": now + (10 * 60),
        "iss": app_id,
    }
    encoded_jwt = jwt.encode(payload, private_key, algorithm="RS256")

    headers = {
        "Authorization": f"Bearer {encoded_jwt}",
        "Accept": "application/vnd.github+json",
    }
    url = f"https://api.github.com/app/installations/{installation_id}/access_tokens"
    resp = requests.post(url, headers=headers, timeout=10)
    resp.raise_for_status()
    return resp.json()["token"]


def _already_notified(issue, notify_repo, headers):
    search_term = f"[{issue['repo_name']} #{issue['number']}]"
    url = "https://api.github.com/search/issues"
    params = {
        "q": f'repo:{notify_repo} "{search_term}" in:title is:open',
        "per_page": 1,
    }

    try:
        resp = requests.get(url, headers=headers, params=params, timeout=10)
        if resp.status_code == 200 and resp.json().get("total_count", 0) > 0:
            logger.info(f"[{issue['repo']} #{issue['number']}] Already notified, skipping")
            return True
    except requests.RequestException as e:
        logger.warning(f"Dedup check failed: {e}")

    return False


def notify(issue, analysis, notify_repo, app_id, private_key, installation_id):
    token = _get_app_token(app_id, private_key, installation_id)
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
    }

    if _already_notified(issue, notify_repo, headers):
        return False

    verdict = analysis.get("verdict", "STRETCH")
    label = VERDICT_TO_LABEL.get(verdict, "stretch")
    difficulty = analysis.get("difficulty", "unknown")

    title = f"[{issue['repo_name']} #{issue['number']}] {verdict}: {issue['title']}"
    if len(title) > 256:
        title = title[:253] + "..."

    body = f"""## {issue['title']}

**Source:** [{issue['repo']} #{issue['number']}]({issue['url']})
**Verdict:** {verdict} | **Difficulty:** {difficulty}

---

### Summary
{analysis.get('summary', 'No summary available.')}

### What the fix involves
{analysis.get('fix_description', 'No fix description available.')}

### Skills needed
{', '.join(analysis.get('skills_needed', ['unknown']))}

### Why this verdict
{analysis.get('verdict_reason', 'No reason provided.')}

---
*Generated by [github-issue-monitor](https://github.com/gracesmith6504/github-issue-monitor)*"""

    url = f"https://api.github.com/repos/{notify_repo}/issues"
    payload = {
        "title": title,
        "body": body,
        "labels": [label],
    }

    try:
        resp = requests.post(url, headers=headers, json=payload, timeout=10)
        if resp.status_code == 201:
            issue_url = resp.json().get("html_url")
            logger.info(f"Notification created: {issue_url}")
            return True
        else:
            logger.error(f"Failed to create notification: {resp.status_code} {resp.text[:200]}")
            return False
    except requests.RequestException as e:
        logger.error(f"Failed to create notification: {e}")
        return False
